# Set up to run the an Android build script per the Travis CI documentation
# Runs the script ./gradlew build connectedCheck
language: android
android:
  components:
    # Use the latest revision of the Android SDK Tools
    - platform-tools
    - tools
    # Use the Android build tools and Android SDK specified in build.gradle
    - build-tools-23.0.3
    - android-23
    # Make the android and google extras available
    - extra-android-support
    - extra-android-m2repository

# Notify the World Wind team mailing list when the build fails and when the build subsequently fixed
notifications:
  email:
    recipients:
      secure: bP6S183XGhm8CuClFO6MEnjUreksvFqtwvaR/17n/iyhsFSFnxHOrEOMa8Zvg6lQKGHGn3IEw6z0y8xrgbOBNA+B4Te/LXTft65mhL/H16WbSWuIKC3RZR8aRN+cPZaUhYHT7+Q2xQclVra4h01AUw1Q97wIHNojV1pryEGo7wgjJguEKb36bbapOQ61/+695FSMDLmysUaOx8NdevzKiKKiVKp4nWGHQOcBRh3R1t7dSI4OBI7rHcwRhqoavv4N6IuLctCC9BcELGfPX2vC/JRlSMGsIE1wViG+jT/kk1lQzvzjh1o5yttm/V6BV8xykMRizGr/h3Luyf4jSDCsQijxcHQDVA/Nnq4AKtxyx5ibZRitrCEJex2LB0QZ6ItSJnbPNUv4QqQerYcsDolS+GUn0iSpy/ENXf2X/Zh+qWSMqR0aploz18pVGCpotjpMm2V156JetTBIhdNtIhdjHJkPh+T/D31Rk4X6ZAuq6azOETj6uzAp43qspXs6hVfhj9U8bJCIM6Gt+el7WejighABxEXVPP7PvqQDzbw7LOnKZmS2vQ6Cdwf+L8hLoe66rahOWMtC+jQVCVaqmWe8w/4jGGMeo3RSoCL1oyi5RzOJ3zwz46YyyQAIDqijsgHWTCmlye4Yo9pSoFKpFK02QDZKU/7u38awgHzYfqFd6BY=
    on_success: change
    on_failure: always

# Reduce the maximum JVM memory used by gradle to avoid termination by the Travis CI container
# during the gradle lint task
env:
  - GRADLE_OPTS="-Xmx512m -XX:MaxPermSize=512m"

# Use the caching configuration per the Travis CI documentation
# See https://docs.travis-ci.com/user/languages/android#Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/