# Directs the Travis CI build service for World Wind Android
# For more information see https://docs.travis-ci.com/user/customizing-the-build/

# Required to install the jq JSON filter used to parse GitHub API results
sudo: required

# Set up to run the Android build script per the Travis CI documentation
language: android

jdk:
  # Configure the build to use Oracle JDK 8, required by Android API 24
  - oraclejdk8

android:
  components:
    - platform-tools      # latest SDK platform-tools
    - tools               # latest SDK tools
    - android-24          # SDK version used to compile the project
    - build-tools-25.0.3  # build tools used by the project
    - extra-android-support
    - extra-android-m2repository

before_script:
  # Prepare the Travis build environment
  - 'if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]]; then openssl aes-256-cbc -K "${encrypted_2eaf8cabe659_key}" -iv "${encrypted_2eaf8cabe659_iv}" -in keystore.jks.enc -out keystore.jks -d; fi'

script:
  # Build the project
  - ./gradlew build --stacktrace

deploy: # by default, travis will not invoke this step for PRs
  # Publish SNAPSHOT artifacts to OJO
  - provider: script
    script: ./gradlew worldwind:artifactoryPublish --stacktrace
    skip_cleanup: true
    on:
      branch: develop
  # Publish release artifacts to Bintray/JCenter and add the documentation to ghpages. Create a changelog for GitHub.
  - provider: script
    script: ./gradlew worldwind:bintrayUpload --stacktrace && travis/ghpages.sh && travis/create_changelog.sh
    skip_cleanup: true
    on:
      tags: true
  # Publish artifacts to GitHub release
  - provider: releases
    api_key: $GITHUB_API_KEY
    file:
      - worldwind/build/outputs/aar/worldwind-debug.aar
      - worldwind/build/outputs/aar/worldwind-release.aar
      - worldwind/build/outputs/doc/worldwind-javadoc.zip
      - worldwind-examples/build/outputs/apk/worldwind-examples-release.apk
      - worldwind-examples/build/outputs/apk/worldwind-examples-debug.apk
      - worldwind-tutorials/build/outputs/apk/worldwind-tutorials-release.apk
      - worldwind-tutorials/build/outputs/apk/worldwind-tutorials-debug.apk
      - CHANGELOG.md
    skip_cleanup: true
    on:
      tags: true

after_failure:
  # Concatenate the logcat.log file et al to the travis log
  - for file in *.log; do echo "$file"; echo "====================="; cat "$file"; done || true

before_cache:
  # Use the caching configuration per the Travis CI documentation
  # See https://docs.travis-ci.com/user/languages/android#Caching
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    # Use the caching configuration per the Travis CI documentation
    # See https://docs.travis-ci.com/user/languages/android#Caching
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

notifications:
  # Notify the World Wind services mailing list on every build
  email:
    recipients:
      secure: SheoPrZZHX1c70JTwoRULza5XobdTPisIgQSfpFBSjolS/Z+qJBIZkyQNKRPfzvs5FEZNBHlaXnvAEX8sUHAJtvp5A9P/c0jaZ3dA0IQ1TJCNg3XT2ZLz4R5JOQclYbgBIqr27MSmx9vvnfGUDCSKaRXdLxmB0Hun7zlkR79IEQ6lLeeB9pu7N/4vuzdmMGKU1lOWs3tmDpdeNOdgSYhKW81eX0FHrgWTXeXcv/3hhtn87XogwKdVKeYFKY+1wHUV3j+dnqeN7yMhqlpljHkOpQ5YqG7nDnPbSJZJ2NINTB/+Mus57eq67FnNl4CDAsWue97wrY8u/+mtGP0boyhXUlBaKJdJpENnuSbxLZtMzvrI5JucxgGXiKei+q84DAh1BbN0+205kBfQgh24GF68bMuKFSpJDobN6usLXVnfjnTrlrMkJQ9wGY/m8g9P9IhJpguJuhYocB6ByMOCkkeSEXdVN6Wb7MGXcfSWdnasVhqAX4yYUt34WUO+vWf842atzXWMZDyStjUe/hWQactB2FhyZBt9kIjMBMWodEhAlDPgFSzwz4huiDkAjeQSszqDQQVOXGFG+f64HhnhYElkY7F08/Yy/sI5HlQ0C0nlNXVsFZ5oHRWwyw02tVVdzNo3ho2h1NSW935S0z3rWRlNOxxKisBON0OBGgZdWJRLYc=
    on_success: always
    on_failure: always
