language: android

android:
  components:
  # Use the latest revision of the Android SDK Tools
  - platform-tools
  - tools
  # Use the Android build tools and Android SDK specified in build.gradle
  - build-tools-23.0.3
  - android-23
  # Make the android and google extras available
  - extra-android-support
  - extra-android-m2repository
  - extra-google-m2repository

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/