# Set up to run the Android build script per the Travis CI documentation
language: android

android:
  components:
    - platform-tools      # latest SDK platform-tools is v23.0.1 (but lint wants 24.0.1 for NewApi check)
    - tools               # latest SDK tools
    - android-24          # SDK version used to compile project
    - build-tools-24.0.3  # build tools used by the project
    - extra-android-support
    - extra-android-m2repository

env:
  global:
    # TODO: Create a GITHUB_API_KEY for nasaworldwind.github.io
    # GITHUB_API_KEY personal access token for Travis to access GitHub Pages
    #- secure: "QEY1qgORKmYdBmvIuDmPpBeBuiy6miLTpBTwfBxuhQEhms3pnDMB0EpllURCR6bgq/AxVy+SCo98gjVo8OhXDFW1bfzs7CjSyvx/5lfY5RfIcdRknXV/M+jiqr2QADj5g73rnECQTWNm1VEA4GxNbpHQfjxs/9aPs4XlOeMwBwRi3/OLzVf74PGwiwX8rB5zU1S/BRDHGKv6d6l8iTCFreDTl5NxCa5FzwLwyBXggSWKwrl7bBWgm8eh9UHHTCF/xKGrjYCvsBbntBflhdZv/K75RsB68tFktUvPhdstOAfIhhEEBgYc5JlwzU+xrR/7XccBuLsp2+Vsokj0VaiwVp8UhgjjSRp9sno1NB5tcUXsFTKW2uZLHKecoQdKA0CBu6O6WmDZG6OgcKJ6NU+Ma566jwg90iDGxJvaO3R3JExlZxqaJWp2qnC7CCpF5MRC+l3PgD20a8DP0pNTJx6GtIeqzuv4smPgVS6il+dwPH/zQqQX23F5xVz7oFmrtgVkfM96Wq7KP++1X/rd9asXLdtd9BzvlJBeHsuAY6b8w0eVIZojrOoL1QrSwu4w6WV3cTOUq3ficbtKQOsU4ySKjaRQj10+11LdD1I3MQZB53/WUyKXV60id1FA2mDzJf8n8kOrcuZfo9MJQElIqlyeEkKtnZffdWbTmfEwPdB75ts="
    # GitHub Pages repo URL sans protocol
    - GH_PAGES_REPO="github.com/NASAWorldWind/NASAWorldWind.github.io"
    # GitHub Pages directory name for the cloned repo
    - GH_PAGES_DIR="gh_pages"
    # Uncomment to test the cron job logic
    #- TRAVIS_EVENT_TYPE="cron"

# Configure the build to use Oracle JDK 8, which is required to compile for Android API 24 and newer
jdk:
  - oraclejdk8

# Notify the World Wind services mailing list on every build
notifications:
  email:
    recipients:
      secure: SheoPrZZHX1c70JTwoRULza5XobdTPisIgQSfpFBSjolS/Z+qJBIZkyQNKRPfzvs5FEZNBHlaXnvAEX8sUHAJtvp5A9P/c0jaZ3dA0IQ1TJCNg3XT2ZLz4R5JOQclYbgBIqr27MSmx9vvnfGUDCSKaRXdLxmB0Hun7zlkR79IEQ6lLeeB9pu7N/4vuzdmMGKU1lOWs3tmDpdeNOdgSYhKW81eX0FHrgWTXeXcv/3hhtn87XogwKdVKeYFKY+1wHUV3j+dnqeN7yMhqlpljHkOpQ5YqG7nDnPbSJZJ2NINTB/+Mus57eq67FnNl4CDAsWue97wrY8u/+mtGP0boyhXUlBaKJdJpENnuSbxLZtMzvrI5JucxgGXiKei+q84DAh1BbN0+205kBfQgh24GF68bMuKFSpJDobN6usLXVnfjnTrlrMkJQ9wGY/m8g9P9IhJpguJuhYocB6ByMOCkkeSEXdVN6Wb7MGXcfSWdnasVhqAX4yYUt34WUO+vWf842atzXWMZDyStjUe/hWQactB2FhyZBt9kIjMBMWodEhAlDPgFSzwz4huiDkAjeQSszqDQQVOXGFG+f64HhnhYElkY7F08/Yy/sI5HlQ0C0nlNXVsFZ5oHRWwyw02tVVdzNo3ho2h1NSW935S0z3rWRlNOxxKisBON0OBGgZdWJRLYc=
    on_success: always
    on_failure: always

before_script: |
  # Clone the GitHub Pages repo to so it can be updated with javadoc and test reports.
  # Ensure script(s) can be executed (req'd if scripts are created in Windows)
  chmod +x gradlew
  chmod +x travis/*.sh
  ./travis/clone_github_pages.sh

script: |
  # Build the project
  ./gradlew build

after_failure: |
  # Concatenate the logcat.log file et al to the travis log
  for file in *.log; do echo "$file"; echo "====================="; cat "$file"; done || true

after_success: |
  # Push javadoc to GitHub pages
  ./travis/update_javadoc.sh

after_script: |
  # Push lint and test reports to GitHub pages
  ./travis/update_reports.sh

# Use the caching configuration per the Travis CI documentation
# See https://docs.travis-ci.com/user/languages/android#Caching
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/